---

- include: pre.yml

- name: create and configure S3 buckets
  s3_bucket:
    name: '{{ item }}'
    policy: '{{ aws_s3_buckets[item]["policy"] | default(omit) }}'
    profile: '{{ aws_profile }}'
  with_items: aws_s3_buckets
  register: s3_bucket

- include: post.yml
