---

- include: pre.yml

- name: create and configure S3 buckets
  s3_bucket:
    name: '{{ item }}'
    policy: '{{ buckets[item]["policy"] | default(omit) }}'
    profile: '{{ profile }}'
  with_items: buckets
  register: s3_bucket

- include: post.yml
