---

- name: set changed buckets fact
  set_fact:
    changed_buckets: >
      {{ _aws_s3_bucket.results
         | selectattr("changed") | map(attribute="name") | list | sort }}

- name: remove new buckets from changed buckets fact
  set_fact:
    changed_buckets: '{{ changed_buckets | difference(_aws_s3_new_buckets) }}'


- name: call optional notifier for newly-created buckets
  include: 'roles/{{ notifier_role }}/tasks/main.yml'
  vars:
    message: >
      created new S3 bucket{% if _aws_s3_new_buckets.__len__() != 1 %}s{% endif %}
      {% for bucket in _aws_s3_new_buckets -%}
      <a href="{{ _aws_s3_url }}?bucket={{ bucket }}">{{ bucket }}</a>
      {%- if not loop.last %}, {% endif -%}
      {% endfor %}
      in <a href="{{ _aws_s3_url }}">account {{ aws_profile }}</a>
  when: >
    notifier_role is defined and
    _aws_s3_new_buckets

- name: call optional notifier for modified buckets
  include: 'roles/{{ notifier_role }}/tasks/main.yml'
  vars:
    message: >
      modified bucket
      polic{% if changed_buckets.__len__() == 1 %}y{% else %}ies{% endif %}
      on S3 bucket{% if changed_buckets.__len__() != 1 %}s{% endif %}
      {% for bucket in changed_buckets -%}
      <a href="{{ _aws_s3_url }}?bucket={{ bucket }}">{{ bucket }}</a>
      {%- if not loop.last %}, {% endif -%}
      {% endfor %}
      in <a href="{{ _aws_s3_url }}">account {{ aws_profile }}</a>
  when: >
    notifier_role is defined and
    changed_buckets

- name: call optional notifier for untracked buckets
  include: 'roles/{{ notifier_role }}/tasks/main.yml'
  vars:
    message:
    attachments:
    - color: warning
      mrkdwn_in: ['text']
      text: >
        *WARNING:* S3
        bucket{% if _aws_s3_untracked_buckets.__len__() != 1 %}s{% endif %}
        {% for bucket in _aws_s3_untracked_buckets -%}
        <a href="{{ _aws_s3_url }}?bucket={{ bucket }}">{{ bucket }}</a>
        {%- if not loop.last %}, {% endif -%}
        {% endfor %}
        exist{% if _aws_s3_untracked_buckets.__len__() == 1 %}s{% endif %}
        in <a href="{{ _aws_s3_url }}">account {{ aws_profile }}</a>
        <br/>but
        {% if _aws_s3_untracked_buckets.__len__() == 1 %}is{% else %}are{% endif %}
        not configured by Ansible
  when: >
    notifier_role is defined and
    _aws_s3_untracked_buckets


- name: call optional notifier
  include: 'roles/{{ notifier_role }}/tasks/main.yml'
  vars:
    message: >
      finished running role <b>aws-s3</b>
      on <a href="{{ _aws_s3_url }}">account {{ aws_profile }}</a>
  when: notifier_role is defined
