---

- name: set global facts
  set_fact:
    s3_url: 'https://console.aws.amazon.com/s3/home?region={{ aws_region }}'

- name: call optional notifier
  include: 'roles/{{ notifier_role }}/tasks/main.yml'
  vars:
    message: >
      started running role <b>aws-s3</b>
      on <a href="{{ s3_url }}">account {{ aws_profile }}</a>
  when: notifier_role is defined


- name: list existing buckets
  command: >
    aws s3api list-buckets
              --query 'Buckets[].Name'
              --profile '{{ aws_profile }}'
  changed_when: False
  register: existing_buckets

- name: set existing buckets fact
  set_fact:
    existing_buckets: '{{ existing_buckets.stdout | from_json | sort }}'

- name: set new buckets fact
  set_fact:
    new_buckets: '{{ buckets | difference(existing_buckets) | sort }}'

- name: set untracked buckets fact
  set_fact:
    untracked_buckets: '{{ existing_buckets | difference(buckets) | sort }}'
